INSERT INTO COUNTRY (name) VALUES ('Sri Lanka');
INSERT INTO COUNTRY (name) VALUES ('India');
INSERT INTO COUNTRY (name) VALUES ('America');
INSERT INTO COUNTRY (name) VALUES ('Russia');
INSERT INTO COUNTRY (name) VALUES ('Australia');
