DROP TABLE IF EXISTS COUNTRY;

CREATE TABLE COUNTRY (
    id UUID DEFAULT RANDOM_UUID() NOT NULL ,
    name VARCHAR(50) NOT NULL PRIMARY KEY,
    population INT NOT NULL,
    capital VARCHAR(50) NOT NULL
);
